# -*- coding: utf-8 -*-
"""ToyLIGO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c3novEN96wKkS9OVnq-hN3aXD4TFojXt
"""

# --- Toy LIGO-style matched filtering: Colab-safe build (no caas_jupyter_tools) ---
import os, textwrap
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import chirp, correlate, welch, stft
from scipy.stats import norm

# 0) Output folder
out_dir = "./"
os.makedirs(out_dir, exist_ok=True)

# 1) Synthetic data
np.random.seed(42)
fs = 4096.0
duration = 1.0
t = np.linspace(0, duration, int(fs*duration), endpoint=False)
f0, f1 = 30.0, 300.0
signal_amplitude, noise_std = 0.5, 0.5

template = chirp(t, f0=f0, f1=f1, t1=duration, method='linear')
template = template - template.mean()
template = template / np.sqrt(np.sum(template**2))

true_signal = signal_amplitude * template
noise = noise_std * np.random.randn(len(t))
data = true_signal + noise

# 2) Figures: time series, matched-filter, residuals
plt.figure(figsize=(10,4))
plt.plot(t, data, label="Noisy data")
plt.plot(t, true_signal, label="Injected signal", alpha=0.8)
plt.xlabel("Time (s)"); plt.ylabel("Strain (arb. units)")
plt.title("Noisy data with injected gravitational-wave-like signal")
plt.legend(); plt.tight_layout()
plt.savefig(os.path.join(out_dir, "fig1_timeseries.png"), dpi=200); plt.close()

corr = correlate(data, template, mode='same')
max_idx = int(np.argmax(corr))
estimated_time = t[max_idx]
snr = corr[max_idx] / np.std(corr)

plt.figure(figsize=(10,4))
plt.plot(t, corr, label="Matched filter output")
plt.axvline(estimated_time, linestyle="--", label="Estimated signal time")
plt.xlabel("Time (s)"); plt.ylabel("Correlation (arb. units)")
plt.title("Matched filter output (cross-correlation)")
plt.legend(); plt.tight_layout()
plt.savefig(os.path.join(out_dir, "fig2_correlation.png"), dpi=200); plt.close()

residual = data - true_signal
mu_hat, sigma_hat = float(np.mean(residual)), float(np.std(residual))
plt.figure(figsize=(10,4))
plt.hist(residual, bins=60, density=True, alpha=0.7, label="Residual histogram")
x = np.linspace(residual.min(), residual.max(), 400)
plt.plot(x, norm.pdf(x, mu_hat, sigma_hat), label=f"Gaussian fit (μ={mu_hat:.3f}, σ={sigma_hat:.3f})")
plt.xlabel("Residual amplitude"); plt.ylabel("Density")
plt.title("Residuals distribution and Gaussian fit")
plt.legend(); plt.tight_layout()
plt.savefig(os.path.join(out_dir, "fig3_residual_hist.png"), dpi=200); plt.close()

# 3) Whiten + median-subtracted STFT, long window, high overlap, contrast clipped
def whiten_time_series(x, fs, nperseg=1024):
    f_psd, psd = welch(x, fs=fs, nperseg=nperseg)
    psd = np.maximum(psd, 1e-12)
    X = np.fft.rfft(x)
    f_fft = np.fft.rfftfreq(len(x), d=1.0/fs)
    asd = np.sqrt(np.interp(f_fft, f_psd, psd))
    asd = np.maximum(asd, 1e-12)
    return np.fft.irfft(X / asd, n=len(x))

whitened = whiten_time_series(data, fs=fs, nperseg=1024)
f_stft, tau_stft, Zxx = stft(
    whitened, fs=fs, window='hann',
    nperseg=1024, noverlap=int(0.9*1024), nfft=1024, boundary=None
)
Sxx = np.abs(Zxx)**2
Sxx_db = 10*np.log10(Sxx + 1e-12)
Sxx_db_ms = Sxx_db - np.median(Sxx_db, axis=1, keepdims=True)

lo, hi = np.percentile(Sxx_db_ms, 95.0), np.percentile(Sxx_db_ms, 99.5)
plt.figure(figsize=(10,4))
plt.pcolormesh(tau_stft, f_stft, Sxx_db_ms, shading='gouraud', vmin=lo, vmax=hi)
plt.xlabel("Time (s)"); plt.ylabel("Frequency (Hz)")
plt.title("Whitened, median-subtracted spectrogram (long window, high overlap)")
plt.tight_layout()
plt.savefig(os.path.join(out_dir, "fig4_spectrogram.png"), dpi=200); plt.close()

# 4) parameters.tex and CSV
params = [
    ("Sampling rate", f"{fs:.0f} Hz"),
    ("Duration", f"{duration:.2f} s"),
    ("Chirp start frequency", f"{f0:.1f} Hz"),
    ("Chirp end frequency", f"{f1:.1f} Hz"),
    ("Signal amplitude", f"{signal_amplitude:.2f}"),
    ("Noise std. dev.", f"{noise_std:.2f}"),
    ("Estimated arrival time", f"{estimated_time:.4f} s"),
    ("Approx. SNR (toy)", f"{snr:.2f}"),
    ("Residual μ, σ", f"{mu_hat:.3f}, {sigma_hat:.3f}"),
]
params_tex = "\\begin{tabular}{ll}\n\\toprule\nParameter & Value \\\\\n\\midrule\n"
for k, v in params: params_tex += f"{k} & {v} \\\\\n"
params_tex += "\\bottomrule\n\\end{tabular}\n"
open(os.path.join(out_dir, "parameters.tex"), "w").write(params_tex)

pd.DataFrame({"time_s": t, "data": data, "injected_signal": true_signal, "template": template}) \
  .to_csv(os.path.join(out_dir, "timeseries.csv"), index=False)

# 5) LaTeX (modest title + numbered equations + spec description)
tex = r"""
\documentclass[11pt,a4paper]{article}
\usepackage[margin=1.1in]{geometry}
\usepackage{amsmath, amssymb, amsthm}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{siunitx}
\usepackage{hyperref}
\usepackage{microtype}
\usepackage{physics}
\usepackage{csquotes}
\usepackage{caption}
\usepackage{listings}
\usepackage{xcolor}

\hypersetup{colorlinks=true,linkcolor=blue,citecolor=blue,urlcolor=blue}
\title{Finding a Whisper in a Storm: An Intuitive Walkthrough of LIGO-Style Matched Filtering}
\author{}
\date{\today}

\begin{document}
\maketitle

\begin{abstract}
Gravitational waves are faint ripples in spacetime, so faint that even the most sensitive instruments see mostly noise. This document tells the story of how data analysis---especially matched filtering---turns noisy strain measurements into confident detections. We build a minimal, reproducible ``toy detector'': a synthetic chirp hidden inside random noise. We then recover it using the core idea of LIGO's searches, with clear intuition about ``Gaussian'' noise and why correlation is the right question to ask of the data.
\end{abstract}

\section{Generative Model and Hypotheses}
We model the observed strain $d(t)$ as either noise alone or noise plus a signal:
\begin{align}
\mathcal{H}_0:~ d(t) &= n(t), \label{eq:h0}\\
\mathcal{H}_1:~ d(t) &= h(t) + n(t), \label{eq:h1}
\end{align}
where $n(t)$ is a (roughly) stationary random process and $h(t)$ is a deterministic template.

If the noise is (approximately) Gaussian, the likelihood ratio can be expressed with the noise-weighted inner product:
\begin{equation}
(a|b) \equiv 4\,\Re \int_{0}^{\infty} \frac{\tilde a(f)\,\tilde b^{*}(f)}{S_n(f)}\,\mathrm{d}f, \label{eq:inner}
\end{equation}
where tildes denote Fourier transforms and $S_n(f)$ is the one-sided PSD.

\section{Matched Filtering and SNR}
For a template $h$ with relative time shift $\tau$, the SNR time series is
\begin{equation}
\rho(\tau) \equiv \frac{(d | h_\tau)}{\sqrt{(h|h)}}, \qquad
h_\tau(t) \equiv h(t-\tau). \label{eq:snr}
\end{equation}
Peaks of $\rho(\tau)$ indicate times where $d$ contains $h$ most strongly, with \eqref{eq:inner} downweighting noisy bands.

\section{Whitening and Spectrograms}
To visualize features and approximate the weighting in \eqref{eq:inner}, we whiten the data:
\begin{equation}
\tilde x_{\mathrm{w}}(f) \equiv \frac{\tilde x(f)}{\sqrt{S_n(f)}}, \qquad
x_{\mathrm{w}}(t) = \mathcal{F}^{-1}\!\big[\tilde x_{\mathrm{w}}(f)\big]. \label{eq:whiten}
\end{equation}
We then compute an STFT with a long window and high overlap:
\begin{equation}
Z(t_k,f_m) \equiv \sum_{t} x_{\mathrm{w}}(t)\,w(t-t_k)\,e^{-i2\pi f_m t}, \label{eq:stft}
\end{equation}
and plot $10\log_{10}|Z|^2$ after subtracting, for each $f_m$, the median over $t_k$:
\begin{equation}
S_{\mathrm{dB}}^{\mathrm{ms}}(t_k,f_m) \equiv 10\log_{10}\!\big(|Z|^2\big)
~ - ~ \mathrm{median}_{t_k}\!\left[\,10\log_{10}\!\big(|Z|^2\big)\,\right]. \label{eq:medsub}
\end{equation}
Finally, we clip color limits to the $95$th--$99.5$th percentiles of $S_{\mathrm{dB}}^{\mathrm{ms}}$ to enhance contrast.

\section{Figures}
\begin{figure}[h!]\centering
\includegraphics[width=0.95\linewidth]{fig1_timeseries.png}
\caption{Noisy data with injected chirp (unit-energy template scaled by an amplitude) overlaid.}
\end{figure}

\begin{figure}[h!]\centering
\includegraphics[width=0.95\linewidth]{fig2_correlation.png}
\caption{Matched-filter output (toy correlation) vs.\ time. The dashed line marks the peak (estimated arrival time).}
\end{figure}

\begin{figure}[h!]\centering
\includegraphics[width=0.95\linewidth]{fig3_residual_hist.png}
\caption{Residual histogram with Gaussian fit. This is the operational meaning of ``Gaussian'': a bell-shaped distribution with predictable tails.}
\end{figure}

\begin{figure}[h!]\centering
\includegraphics[width=0.95\linewidth]{fig4_spectrogram.png}
\caption{Whitened, median-subtracted spectrogram using a long Hann window with 90\% overlap; color limits clipped to the 95th--99.5th percentiles.}
\end{figure}

\appendix
\section*{Parameters}
\noindent Table~\ref{tab:params} lists the parameters used in the experiment.
\begin{table}[h!]\centering
\caption{Parameters of the toy experiment.}
\label{tab:params}
\input{parameters.tex}
\end{table}

\end{document}
"""
open(os.path.join(out_dir, "ligo_toy_matched_filter.tex"), "w").write(tex)

print("Done. Upload the contents of ./outputs to Overleaf.")